name: Build Create-Simurail

on:
  push:
    paths:
      - 'src/**'
      - 'gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
      - 'build.gradle'
      - 'build.gradle.kts'
      - 'settings.gradle'
      - 'settings.gradle.kts'
      - 'gradle.properties'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set Commit Hash
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Build mod
        run: ./gradlew clean build --stacktrace -PcommitHash="${{ env.SHORT_SHA }}"

      - name: Remove unwanted JAR files
        run: |
          find build/libs -type f -name '*-sources.jar' -delete
          find build/libs -type f -name '*-dev.jar' -delete
          find build/libs -type f -name '*-javadoc.jar' -delete

      - name: Upload mod JAR
        uses: actions/upload-artifact@v7
        with:
          name: Create-Simurail-${{ env.SHORT_SHA }}
          path: build/libs/*.jar
          if-no-files-found: error
          retention-days: 30
